<?php require_once __DIR__ . '/../helpers/basicTopBar.htm'; ?>
<div class="blockCenter">
    <img alt="" id="img1" src="/../../public/images/code_1.jpg">
    <img alt="" id="img2" src="/../../public/images/code_2.jpg">
    <div class="imgHelper" id="imgHelper"></div>
    <div class="textCenter blockCenter">
        <h3>Szukasz osoby, która pomoże Ci stworzyć wymarzoną strone internetową?</h3>
        <br>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fringilla mattis faucibus. Nullam condimentum lacus id scelerisque tristique. Nulla et tempor mauris. Sed euismod, urna in scelerisque iaculis, leo nisi fringilla urna, ac sollicitudin erat libero eu nisl. Proin vulputate sodales nisl, vitae molestie diam tincidunt vitae. Nam molestie, nisi sit amet efficitur maximus, urna est egestas magna, in pellentesque urna enim non dui. Nullam id orci nibh. Nullam laoreet vestibulum dui. Aenean semper urna libero, non tincidunt purus gravida eu. Curabitur facilisis facilisis feugiat. Cras ut elit massa. Cras id mattis tortor. Donec faucibus accumsan tellus id condimentum.</p>
        <br>
        <hr>
        <br>
        <h3>A może potrzebna Ci zwykła wizytówka?</h3>
        <br>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fringilla mattis faucibus. Nullam condimentum lacus id scelerisque tristique. Nulla et tempor mauris. Sed euismod, urna in scelerisque iaculis, leo nisi fringilla urna, ac sollicitudin erat libero eu nisl. Proin vulputate sodales nisl, vitae molestie diam tincidunt vitae. Nam molestie, nisi sit amet efficitur maximus, urna est egestas magna, in pellentesque urna enim non dui. Nullam id orci nibh. Nullam laoreet vestibulum dui. Aenean semper urna libero, non tincidunt purus gravida eu. Curabitur facilisis facilisis feugiat. Cras ut elit massa. Cras id mattis tortor. Donec faucibus accumsan tellus id condimentum.</p>
        <br>
        <hr>
    </div>
</div>
<?php require_once __DIR__ . '/../helpers/basicFooter.htm'; ?>